<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nsc_extended_ce"
 *
 * Auto generated by Extension Builder 2014-04-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Extended CE',
	'description' => 'Extends the default TYPO3 Content Elements with some extra fields.',
	'category' => 'plugin',
	'author' => 'Nicolas Scheidler',
	'author_email' => 'Nicolas.Scheidler@gmail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.2.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>